# Generated by Django 3.0.6 on 2020-06-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('send_to', models.CharField(choices=[('Teacher', 'All Teachers'), ('Student', 'All Students'), ('User', 'All Users (Teachers and Students)')], max_length=10, null=True)),
            ],
        ),
    ]
