# Generated by Django 3.0.6 on 2020-05-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_sailparticipant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sailparticipant',
            name='role',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], default='Student', max_length=10),
        ),
        migrations.AlterField(
            model_name='sailparticipant',
            name='year_in_school',
            field=models.CharField(choices=[('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior')], default='Freshman', max_length=10),
        ),
    ]
