# Generated by Django 3.0.7 on 2020-06-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_sailuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='signed_participant_form',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='signed_photo_form',
            field=models.BooleanField(default=False),
        ),
    ]
