# Generated by Django 3.0.7 on 2020-06-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200612_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='signed_participant_form',
        ),
        migrations.RemoveField(
            model_name='student',
            name='signed_photo_form',
        ),
        migrations.AddField(
            model_name='sailuser',
            name='signed_participant_form',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sailuser',
            name='signed_photo_form',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='signed_medical_form',
            field=models.BooleanField(default=False),
        ),
    ]
