# Generated by Django 3.0.7 on 2020-06-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='follower',
            name='role',
            field=models.CharField(choices=[('Teacher', 'Prospective Teacher'), ('Student', 'Prospective Student'), ('Parent', 'Parent / Interested Person')], default='Teacher', max_length=10),
        ),
    ]
