# Generated by Django 3.0.7 on 2020-06-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200625_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='role',
            field=models.CharField(choices=[('Prospective Teacher', 'Prospective Teacher'), ('Prospective Student', 'Prospective Student'), ('Parent', 'Parent / Interested Person')], default='Prospective Teacher', max_length=20),
        ),
    ]
