# Generated by Django 3.0.7 on 2020-06-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='send_to',
            field=models.CharField(choices=[('Teacher', 'All Teachers'), ('Student', 'All Students'), ('User', 'All Users (Teachers and Students)'), ('Follower', 'Followers (Interested people)')], max_length=10, null=True),
        ),
    ]
