# Generated by Django 3.0.7 on 2020-06-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20200625_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='send_to',
            field=models.CharField(choices=[('Teacher', 'All Teachers'), ('Student', 'All Students'), ('User', 'All Users (Teachers and Students)'), ('Prospective Teacher', 'Prospective Teachers'), ('Prospective Student', 'Prospective Students'), ('Parent', 'Parent / Interested Person'), ('Follower', 'Everyone on interest list')], max_length=20, null=True),
        ),
    ]
