# Generated by Django 3.0.6 on 2020-05-28 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200528_0256'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SailCourse',
            new_name='Course',
        ),
    ]
