# Generated by Django 3.0.6 on 2020-05-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200528_1552'),
        ('courses', '0003_auto_20200528_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(to='users.Teacher'),
        ),
    ]
