# Generated by Django 3.0.6 on 2020-06-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_sailuser_role'),
        ('courses', '0010_course_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, to='users.Student'),
        ),
    ]
