# Generated by Django 3.0.6 on 2020-06-01 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20200601_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 4, 10, 0)),
        ),
    ]
