# Generated by Django 3.0.6 on 2020-05-28 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_auto_20200528_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='SailCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('prior_knowledge', models.CharField(blank=True, max_length=100)),
                ('course_length', models.PositiveSmallIntegerField(default=60)),
                ('capacity_limit', models.PositiveSmallIntegerField(blank=True)),
                ('approved', models.BooleanField(default=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SailTeacher')),
            ],
        ),
    ]
