# Generated by Django 3.0.6 on 2020-05-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200528_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='capacity_limit',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
