# Generated by Django 3.0.6 on 2020-05-29 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20200528_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='capacity_limit',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Leave blank if none.', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='prior_knowledge',
            field=models.CharField(blank=True, help_text='Leave blank if none.', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.CharField(help_text='Students will see this description when they scroll through all the available courses.', max_length=255),
        ),
    ]
