# Generated by Django 3.0.6 on 2020-06-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20200601_0004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['course_name']},
        ),
        migrations.AlterField(
            model_name='course',
            name='course_length',
            field=models.PositiveSmallIntegerField(default=60, help_text='Length of your course in minutes, either 60 or 120.'),
        ),
    ]
