# Generated by Django 3.0.7 on 2020-06-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20200603_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-curated', 'course_name']},
        ),
        migrations.AddField(
            model_name='course',
            name='curated',
            field=models.BooleanField(default=False),
        ),
    ]
